name: release-please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/github-app-token-generator@a9cd374e271b8aef573b8c16ac46c44fb89b02db
        id: get-token
        with:
          private-key: ${{ secrets.TOKENS_PRIVATE_KEY }}
          app-id: ${{ secrets.TOKENS_APP_ID }}
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          token: ${{ steps.get-token.outputs.token }}
          release-type: rust
          package-name: "binary-info"
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - run:
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v3
        with:
          node-version: "*"
          registry-url: "https://registry.npmjs.org"
        if: ${{ steps.release.outputs.release_created }}
      - run: wasm-pack build --target nodejs --release --scope=netlify
        if: ${{ steps.release.outputs.release_created }}
      - run: wasm-pack publish --access public
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
