name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node-version: [14.15.0, "*"]
        exclude:
          - os: macOS-latest
            node-version: 14.15.0
          - os: windows-latest
            node-version: 14.15.0
      fail-fast: false
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      #      - name: Node.js ${{ matrix.node }}
      #        uses: actions/setup-node@v3
      #        with:
      #          node-version: ${{ matrix.node-version }}
      #          cache: "npm"
      #          check-latest: true
      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      #- name: Install Node.js dependencies
      #  run: npm ci
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Rust tests
        uses: actions-rs/cargo@v1
        with:
          command: test
      #- name: Node.js tests
      #  run: npm run test:ci
